# Generated by Django 5.2 on 2025-04-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedies', '0005_remedy_approved_at_remedy_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remedy',
            name='ai_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remedy',
            name='ai_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remedy',
            name='ai_health_benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remedy',
            name='ai_ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remedy',
            name='ai_preparation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remedy',
            name='ai_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
