# Generated by Django 5.2 on 2025-04-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedies', '0006_remedy_ai_accepted_remedy_ai_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remedy',
            name='ai_cleaned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remedy',
            name='original_input',
            field=models.TextField(blank=True, null=True),
        ),
    ]
